### ISSUE TITLE
prefix sitemap(-*).xml to wp-sitemap(-*).xml

### ISSUE THREAD

**Issue by pfefferle** [GoogleChromeLabs/wp-sitemaps#128]
### Description

To prevent collisions with existing plugins, we discussed to rename the `sitemap(-*).xml` to `wp-sitemap(-*).xml`.

The file-name(s) should be also filterable, to help other plugins, that use the new core feature, to be consistent.

**Comment by swissspidy** [comment]
I am not sure whether we should make that prefix filterable. We could just as well hardcode it.

With what would this be consistent?

**Comment by pfefferle** [comment]
If you use one of the current plugins, they mostly generate a `/sitemap.xml` and this might cause some 404s and that could cause issues with Search engines (even if the redirect is implemented). Why not make it filterable? What is the downside?

**Comment by swissspidy** [comment]
https://github.com/GoogleChromeLabs/wp-sitemaps/pull/129#issuecomment-590915627 suggests redirecting requests to `/sitemap.xml` if they'd lead to 404s. So that would be covered.

> Why not make it filterable? What is the downside?

Unnecessary overhead and error-proneness for no real benefit. The sitemap name does not matter for consumers. Worst case there's a redirect or there are two sitemaps running on the site. Still, the correct sitemap would be referenced in robots.txt

**Comment by pfefferle** [comment]
My intention was: Plugin developer like [Google Sitemaps](https://wordpress.org/plugins/google-sitemap-generator/) will be able to keep the existing `/sitemap.xml` slug if they use/extend the core implementation. But true, if we implement https://github.com/GoogleChromeLabs/wp-sitemaps/pull/129#issuecomment-590915627 it shouldn't be a problem.
