### ISSUE TITLE
Flush rewrite rules upon plugin (de)activation

### ISSUE THREAD

**Issue by swissspidy** [GoogleChromeLabs/wp-sitemaps#132]
As mentioned on Slack, we might need to flush rewrite rules using `flush_rewrite_rules( false )` upon plugin activation and deactivation to prevent potential issues with rewrites and other plugins.

Related: #128

**Comment by pbiron** [comment]
thanx for opening this issue!  It was on my todo list but other things kept getting in the way.

A couple of thoughts:

1. currently, rewrite rules are flushed upon initial activation and/or if the plugin's version number changes.  Flushing rewrite rules with a `register_activation_hook()` would be preferable.  As I've been testing this plugin, I've several times switched back-end-forth between it and the plugin I currently use for sitemaps and that's caused problems since when I reactive this plugin (without a version change) then rewrite aren't flushed.

2. using `register_deactivation_hook()` would also help with testing when switching back-end-forth between this and other sitemap plugins.

3. there are likely to be other rewrite rules difficulties when this is merged, since the (de)activation hooks won't be available :-)  The plugin I currently use for sitemaps does not flush rewrite rules upon deactivation, so when this is merged I suspect I suspect I'll have to manually flush rewrite rules after deactivating that other plugin.

[Note: in all the comments I made while testing this plugin, I've avoided mentioning the name of the plugin I current use, because I don't want to appear to be "blaming" that other plugin for problems I've encountered while testing this one.]
