### ISSUE TITLE
Use _n for singular/plural distinction

### ISSUE THREAD

**Issue by ePascalC** [GoogleChromeLabs/wp-sitemaps#177]
The string "This XML Sitemap contains %s URLs" should use the _n function to correctly split singular and plural. 
inc/class-core-sitemaps-stylesheet.php:52 and 137

**Comment by pbiron** [comment]
This one is tough.

The number of URLs is not known at the time that statement is executed.  And `_n_noop()` isn't appropriate either because, in fact, the number of URLs isn't known from within PHP so `translate_nooped_plural()` can't be used later.

A somewhat analogous case would be a string in the `content:` property of a CSS rule, where the single vs plural choice isn't known until the HTML is loaded by the browser :-(

Would something like the following be OK for translators?

```
$singular_text = sprintf(
	/* translators: %s: number of URLs. */
	_x( 'This XML Sitemap contains %s URL.', 'singular number of URLs', 'core-sitemaps' ),
	'<xsl:value-of select="count( sitemap:urlset/sitemap:url )"/>'
);
$plural_text = sprintf(
	/* translators: %s: number of URLs. */
	_x( 'This XML Sitemap contains %s URLs.', 'plural number of URLs', 'core-sitemaps' ),
	'<xsl:value-of select="count( sitemap:urlset/sitemap:url )"/>'
);
```

The other complication here is that PHP's `number_format_i18n()` isn't available to format the number for the locale.  But I think I can reverse engineer that in XSLT.

**Comment by swissspidy** [comment]
No, that wouldn‘t work for all languages because of different plurals.

Due to the limitations you mention, this is essentially a wontfix.

We can only optimize the string a little bit like #176 does. But that‘s about it.

**Comment by pbiron** [comment]
> No, that wouldn‘t work for all languages because of different plurals.

When I first read your reply, I didn't understand it.  A little searching turned up https://www.cssigniter.com/wordpress-localization-plural-forms-work/.  Very informative,..now I understand why my suggestion wouldn't work.

BTW, `number_format_i18n()` will be easy to implement in XSLT.

**Comment by pbiron** [comment]
Oh, there actually is a way we can use `_n()`.  

If we generate the stylesheet URL in `Core_Sitemaps_Renderer::get_sitemap_xml()` (instead of in the constructor, which should be fine since that's the only place it's used) then:

1. we'll know how many URLs are in the sitemap
2. we can add a query_arg to the URL with the count

like so,

```
$stylesheet_url = $this->get_sitemap_stylesheet_url();
if ( $stylesheet_url ) {
	$stylesheet_url = add_query_arg( 'number-of-urls', count( $url_list ), $stylesheet_url );
	$stylesheet_pi = '<?xml-stylesheet type="text/xsl" href="' . esc_url( $stylesheet_url ) . '" ?>';
}
```

Then, in `Core_Sitemaps_Stylesheet::get_sitemap_stylesheet()` we can do:

```
$text = sprintf(
	/* translators: %s: number of URLs. */
	_n(
		'This XML Sitemap contains %s URL.',
		'This XML Sitemap contains %s URLs.',
		isset( $_GET['number-of-urls'] ) ? absint( $_GET['number-of-urls'] ) : 0,
		'core-sitemaps'
	),
	'<xsl:value-of select="count( sitemap:urlset/sitemap:url )" />'
);
```

**Comment by swissspidy** [comment]
Thanks a lot for looking closely into this!

While such a solution might sound appealing, it would also make this overly complex for very little benefit.

I still think changing the sentence like in #176 is the only way to go. And I say this as someone who is very familiar with i18n.
