### ISSUE TITLE
Registry / Main Class discussion

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#44]
> There's a question whether the `Core_Sitemaps` class and `Core_Sitemaps_Registry` have the same purpose, but I think to keep the main class as lean as possible, only to use it for setup.

I've been thinking about this as well. I definitely think the registry could be a part of the main Sitemaps class. Let's do this in a separate issue to avoid rabbit holing for now.

_Originally posted by @joemcgill in https://github.com/GoogleChromeLabs/wp-sitemaps/pull/42#issuecomment-549842666_

**Comment by joemcgill** [comment]
For now, I think it's ok to leave the registry as it's own class as an architectural decision, but it should be saved as a property of the main `Core_Sitemaps` object so that any code that is integrating with the sitemaps can access the registry without passing it around as a dependency.

Right now, we've got an established pattern where each object type provider is being passed the registry in order to register itself. However, it would be much cleaner if each provider would expose the properties of itself which is needed to register itself and leave all registration to the registry rather than having providers need to know anything about a registration object.

I'm going to refactor this a little so we have the following:

1. The main sitemap class should be responsible for knowing about the registry (for now, implemented by the `Core_Sitemaps_Registry` class).
2. Each site map provider will expose properties of itself needed to be added to the provider registry.
3. The registry will be responsible for setting up each sitemap that has been provided so that rewrite rules are in place and callbacks are available to query and render sitemaps for each object type.
