### ISSUE TITLE
optimize max_num_pages

### ISSUE THREAD

**Issue by svandragt** [GoogleChromeLabs/wp-sitemaps#73]
we should explore ways of doing this more performantly than querying the first page for each subtype.

_Originally posted by @joemcgill in https://github.com/GoogleChromeLabs/wp-sitemaps/pull/72/files_

**Comment by joemcgill** [comment]
A good first step here would be to evaluate the methods for each sitemap provider and document what the specific performance issues exist that we can improve.

**Comment by joemcgill** [comment]
Let's spike this out during the next sprint with the goal being to gather research results on what the performance impact is of calculating the max number of pages for each sitemap provider and determine if there are better approaches that could be implemented.

**Comment by joemcgill** [comment]
Now that #90 has landed, there are less performance concerns, since `max_num_pages()` are only calculated once, when rendering the index, and not when sitemaps are registered. I've opened a small bugfix (#92) while investigating the performance of these methods, but I think this particular issue can now be closed.
